---
title: "Quality Alloys"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard

library(tidyverse)

setwd("C:/Users/baptista.leonardo/Documents/ESPM SI/4°Semestre/R")

dados = readxl::read_excel("Lista_de_exercicios_1.xlsx")


dados2 = select(dados,"Week (2008-2009)", "Period", "Avg. Time on Site (secs.)", "Profit")

dados2 = rename(dados2, Semana = "Week (2008-2009)")
dados2 = rename(dados2, Período = "Period")
dados2 = rename(dados2, Tempo_no_site = "Avg. Time on Site (secs.)")
dados2 = rename(dados2, Lucro = "Profit")

dados2$Período = factor(dados2$Período, levels = c("Shakedown", "Analysis 1", "Promotion", "Analysis 2"))

```


```{r}
# Reactive that returns the whole dataset if there is no brush
selectedData <- reactive({
  data <- brushedPoints(dados2, input$plot_brush)
  if (nrow(data) == 0)
    data <- dados2
  data
})
```

Column {data-width=650}
-----------------------------------------------------------------------

### Diagrama de dispersão entre o tempo médio no site e o lucro {data-width=600}

```{r}
library(ggplot2)
renderPlot({
  
ggplot(dados2, aes(x = Tempo_no_site, y = Lucro, color = Período)) + geom_point(size = 3, alpha=0.7) + labs(title = "Diagrama de dispersão entre o tempo médio no site e o lucro.", subtitle = "Dados de 2008-2009", x = "Tempo no site", y = "Lucro", color="Período") + theme_classic()
  
  
}, outputArgs = list(brush = brushOpts(id = "plot_brush")))
```

### Lucro por período

```{r}
renderPlot({
  
ggplot(selectedData(), aes(y = Lucro, x = Período, fill= Período)) + geom_boxplot() + labs(title = "Lucro por período", subtitle = "Dados de 2008-2009", x = "", y = "Lucro", fill="Período") + scale_fill_brewer(palette = "Oranges") + theme_classic() + guides(fill="none")
  
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Period Details {data-width=400}

```{r}

renderTable({
  selectedData()
})

```
